# Agent配置文件

# 元Agent配置
meta_agent:
  name: "MetaAgent"
  description: "负责意图识别和路由的元Agent"
  enabled: true
  routing_timeout: 30

# 教育Agent配置
edu_agent:
  name: "EduAgent"
  description: "负责处理教育相关问题的Agent"
  enabled: true
  max_response_length: 1000
  ollama_model: "qwen:0.5b"
  temperature: 0.7
  knowledge_base:
    - "math"
    - "language"
    - "science"
    - "history"
    - "geography"

# 情感Agent配置
emotion_agent:
  name: "EmotionAgent"
  description: "负责处理情感相关问题的Agent"
  enabled: true
  max_empathy_responses: 5
  emotion_detection: true
  ollama_model: "qwen:0.5b"
  temperature: 0.8

# 安全Agent配置
safety_agent:
  name: "SafetyAgent"
  description: "负责内容安全审查的Agent"
  enabled: true
  max_retry_attempts: 3
  ollama_model: "qwen:0.5b"
  temperature: 0.0
  rejection_categories:
    - "violence"
    - "inappropriate_content"
    - "privacy"
    - "dangerous_behavior"
    - "negative_emotions"

# 记忆Agent配置
memory_agent:
  name: "MemoryAgent"
  description: "负责存储和检索对话历史的Agent"
  enabled: true
  max_history_length: 100
  persistence_enabled: true
  persistence_interval: 300  # 秒

# Agent间通信配置
agent_communication:
  timeout: 60
  retry_attempts: 3
  message_format: "json"

# Agent模型配置
agent_models:
  edu_agent:
    model_name: "qwen:0.5b"
    temperature: 0.7
    max_tokens: 500
  emotion_agent:
    model_name: "qwen:0.5b"
    temperature: 0.8
    max_tokens: 300
  safety_agent:
    model_name: "qwen:0.5b"
    temperature: 0.0
    max_tokens: 200

# Agent负载均衡配置
load_balancing:
  strategy: "round_robin"
  health_check_interval: 30

# 模型管理配置
model_management:
  mlflow:
    tracking_uri: "http://localhost:5000"
    experiment_name: "edu-ai-agents"
    model_name: "qwen-agents"
  ab_testing:
    enabled: true
    variants:
      - name: "qwen-0.5b"
        model: "qwen:0.5b"
        traffic_percentage: 70
      - name: "llama2"
        model: "llama2"
        traffic_percentage: 30
  rollback:
    enabled: true
    max_versions: 5