# 音频配置文件

# 音频处理设置
audio_processing:
  sample_rate: 22050
  channels: 1
  bit_depth: 16
  format: "wav"

# 语音识别设置
speech_recognition:
  language: "zh-CN"
  timeout: 10
  phrase_time_limit: 5
  energy_threshold: 300
  pause_threshold: 0.8

# 语音合成设置
speech_synthesis:
  default_voice: "zh-CN"
  speaking_rate: 1.0
  pitch: 1.0
  volume_gain_db: 0.0

# 音频预处理设置
preprocessing:
  normalize: true
  remove_silence: true
  silence_threshold: 0.01
  min_silence_duration: 0.5

# 音频编码设置
encoding:
  codec: "pcm_s16le"
  container: "wav"
  compression_level: 0

# 声纹验证设置
voice_verification:
  similarity_threshold: 0.8
  enrollment_samples: 3
  verification_attempts: 3

# 音频质量设置
quality:
  min_duration: 0.1  # 最小音频时长(秒)
  max_duration: 30.0  # 最大音频时长(秒)
  min_volume: 0.01    # 最小音量阈值
  max_volume: 1.0     # 最大音量阈值