# 日志配置文件

# 根日志配置
root:
  level: "INFO"
  handlers: ["console", "file"]

# 日志器配置
loggers:
  EduAI:
    level: "DEBUG"
    handlers: ["console", "file", "error_file"]
    propagate: false
  
  EduAI.agents:
    level: "INFO"
    handlers: ["file"]
    propagate: false
    
  EduAI.api:
    level: "INFO"
    handlers: ["api_file"]
    propagate: false
    
  EduAI.audio:
    level: "WARNING"
    handlers: ["audio_file"]
    propagate: false
    
  EduAI.database:
    level: "INFO"
    handlers: ["database_file"]
    propagate: false

# 处理器配置
handlers:
  console:
    class: "logging.StreamHandler"
    level: "INFO"
    formatter: "simple"
    stream: "ext://sys.stdout"
    
  file:
    class: "logging.handlers.RotatingFileHandler"
    level: "DEBUG"
    formatter: "detailed"
    filename: "logs/edu_ai.log"
    maxBytes: 10485760  # 10MB
    backupCount: 5
    
  error_file:
    class: "logging.handlers.RotatingFileHandler"
    level: "ERROR"
    formatter: "detailed"
    filename: "logs/error.log"
    maxBytes: 10485760  # 10MB
    backupCount: 5
    
  api_file:
    class: "logging.handlers.RotatingFileHandler"
    level: "INFO"
    formatter: "api"
    filename: "logs/api.log"
    maxBytes: 10485760  # 10MB
    backupCount: 3
    
  audio_file:
    class: "logging.handlers.RotatingFileHandler"
    level: "WARNING"
    formatter: "detailed"
    filename: "logs/audio.log"
    maxBytes: 5242880  # 5MB
    backupCount: 3
    
  database_file:
    class: "logging.handlers.RotatingFileHandler"
    level: "INFO"
    formatter: "database"
    filename: "logs/database.log"
    maxBytes: 10485760  # 10MB
    backupCount: 3

# 格式化器配置
formatters:
  simple:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    
  detailed:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(module)s - %(funcName)s - %(message)s"
    
  api:
    format: "%(asctime)s - API - %(levelname)s - %(remote_addr)s - %(method)s %(url)s - %(status_code)s - %(message)s"
    
  database:
    format: "%(asctime)s - DATABASE - %(levelname)s - %(operation)s - %(table)s - %(message)s"

# 日志级别定义
levels:
  DEBUG: 10
  INFO: 20
  WARNING: 30
  ERROR: 40
  CRITICAL: 50

# 特殊配置
special:
  # 是否启用日志着色
  colorize: true
  
  # 日志文件目录
  log_directory: "logs"
  
  # 是否启用日志轮转
  rotate_logs: true
  
  # 是否在应用启动时清理旧日志
  cleanup_on_startup: false