# Web配置文件

# Flask应用配置
flask:
  host: "0.0.0.0"
  port: 5000
  debug: false
  threaded: true
  processes: 1

# API配置
api:
  version: "v1"
  base_path: "/api"
  rate_limiting:
    enabled: true
    requests_per_minute: 60
  cors:
    enabled: true
    origins:
      - "http://localhost:8501"  # Streamlit默认端口
      - "http://127.0.0.1:8501"
    methods:
      - "GET"
      - "POST"
      - "PUT"
      - "DELETE"
    headers:
      - "Content-Type"
      - "Authorization"

# WebSocket配置
websocket:
  enabled: true
  async_mode: "threading"
  cors_allowed_origins:
    - "*"
  logger: false
  engineio_logger: false

# Session配置
session:
  secret_key: "edu-ai-system-secret-key"
  permanent_session_lifetime: 3600  # 秒

# 安全配置
security:
  jwt_secret_key: "edu-ai-jwt-secret-key"
  jwt_expiration_delta: 3600  # 秒
  password_hash_method: "sha256"

# 缓存配置
cache:
  type: "simple"
  default_timeout: 300  # 秒

# 日志配置
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/web.log"

# 静态文件配置
static:
  folder: "static"
  url_path: "/static"

# 模板配置
templates:
  folder: "templates"

# 健康检查配置
health_check:
  enabled: true
  endpoint: "/health"
  response:
    status: "healthy"
    message: "Education AI System is running"

# 压缩配置
compression:
  enabled: true
  threshold: 1024  # 字节